import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">

        {/* Navbar (Top) */}
        <Navbar />

        {/* Page Content */}
        <main className="flex-1 flex flex-col">
          {children}
        </main>

        {/* Footer (Bottom) */}
        <Footer />

      </body>
    </html>
  );
}